"""Alembic environment.

The database URL comes from the application's settings object rather than from
``alembic.ini``, so a migration cannot run against a different database than
the app reads, and no credential is written into a committed file.

Two filters matter for autogenerate correctness:

* **PostGIS's own tables are ignored.** ``spatial_ref_sys`` and friends belong
  to the extension. Without this filter, the first autogenerated migration
  would cheerfully propose dropping them.
* **GeoAlchemy2's managed indexes are ignored.** It creates spatial indexes as
  a side effect of the column type; autogenerate would otherwise see them as
  unexpected and try to drop them on every run.
"""

from __future__ import annotations

import sys
from logging.config import fileConfig
from pathlib import Path
from typing import Any

from alembic import context
from geoalchemy2 import alembic_helpers
from sqlalchemy import engine_from_config, pool

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from raceos.config import get_settings  # noqa: E402
from raceos.db.models import Base  # noqa: E402
from raceos.db.session import normalise_database_url  # noqa: E402

config = context.config

if config.config_file_name is not None:
    # `disable_existing_loggers` defaults to True, which would switch off every
    # logger already created — including the application's own, since env.py
    # imports raceos modules above. That silently suppressed the startup log
    # line in any process that had run a migration first, and it would do the
    # same to a real deployment if migrations and the app ever shared one.
    fileConfig(config.config_file_name, disable_existing_loggers=False)

target_metadata = Base.metadata

#: Tables owned by the PostGIS extension, not by this application.
POSTGIS_TABLES = frozenset(
    {"spatial_ref_sys", "geometry_columns", "geography_columns", "raster_columns", "raster_overviews"}
)


def include_object(
    obj: Any, name: str | None, type_: str, reflected: bool, compare_to: Any
) -> bool:
    if type_ == "table" and name in POSTGIS_TABLES:
        return False
    # GeoAlchemy2 knows which of its own managed objects autogenerate should
    # ignore — spatial indexes it creates as a side effect of the column type,
    # and the extension's internal views. Delegating is more durable than
    # pattern-matching their names ourselves.
    return bool(alembic_helpers.include_object(obj, name, type_, reflected, compare_to))


def _url() -> str:
    return normalise_database_url(get_settings().database_url.get_secret_value())


def run_migrations_offline() -> None:
    """Emit SQL to stdout without connecting. ``alembic upgrade head --sql``."""
    context.configure(
        url=_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_object=include_object,
        render_item=alembic_helpers.render_item,
        compare_type=True,
        compare_server_default=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    section = config.get_section(config.config_ini_section) or {}
    section["sqlalchemy.url"] = _url()

    connectable = engine_from_config(section, prefix="sqlalchemy.", poolclass=pool.NullPool)

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_object=include_object,
            render_item=alembic_helpers.render_item,
            compare_type=True,
            compare_server_default=True,
            # One transaction for the whole upgrade: a migration that fails
            # half way leaves no partially-migrated schema behind.
            transaction_per_migration=False,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
