"""initial schema

Revision ID: 93f5c4c7f83a
Revises: 
Created: 2026-08-29 22:39:06.304536

Every migration is reversible: ``downgrade()`` is written and exercised, not
left as a stub. Breaking changes follow expand-contract — add the new column,
backfill in a job, dual-write, switch reads, drop the old column in a LATER
release — so the previous image always runs against the new schema.
"""
from __future__ import annotations

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql
revision: str = '93f5c4c7f83a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None



# Every native enum type this migration creates. SQLAlchemy emits CREATE TYPE
# as a side effect of the first column that uses one, but autogenerate does
# NOT emit the matching DROP TYPE — so without this list a downgrade leaves
# the types orphaned and the next upgrade fails with
# `type "distance_type" already exists`. Reversibility is a requirement, so
# the drops are explicit.
ENUM_TYPES = (
    "account_state",
    "admin_role",
    "athlete_level",
    "bag_key",
    "bike_helmet_enum",
    "bike_position_enum",
    "bundle_status",
    "coach_link_status",
    "compare_state",
    "constraint_source",
    "crowd_category",
    "crowd_confidence",
    "crowd_status",
    "currency",
    "difficulty",
    "distance_type",
    "drift_cause",
    "drift_sensitivity",
    "drift_severity",
    "drift_status",
    "feasibility",
    "incident_severity",
    "leg",
    "margin_state",
    "notification_severity",
    "notification_type",
    "plan_status",
    "provenance",
    "purchase_status",
    "race_file_format",
    "race_file_status",
    "race_status",
    "refund_reason",
    "service_status",
    "share_scope",
    "solve_job_status",
    "subscription_status",
    "surface_quality",
    "unit_system",
    "user_tier",
)

# Tables carrying `updated_at`, which the trigger below maintains. Listed
# explicitly so this migration is a complete, readable statement of what it
# does rather than something that introspects at run time.
UPDATED_AT_TABLES = (
    "admin_roles",
    "analysis_actions",
    "analysis_calibrations",
    "analysis_compare_rows",
    "cache_entries",
    "coach_athlete_links",
    "coach_notes",
    "constraints",
    "course_bundle_legs",
    "course_bundles",
    "courses",
    "crowd_reports",
    "idempotency_keys",
    "incidents",
    "invoices",
    "kpi_snapshots",
    "notification_preferences",
    "notifications",
    "plan_aid_actions",
    "plan_bag_items",
    "plan_bags",
    "plan_constraint_refs",
    "plan_drift_events",
    "plan_fuelling",
    "plan_gates",
    "plan_segments",
    "plan_splits",
    "plans",
    "post_race_analyses",
    "post_race_files",
    "price_catalog",
    "purchases",
    "push_subscriptions",
    "races",
    "rate_limit_counters",
    "service_health",
    "sessions",
    "share_links",
    "solve_jobs",
    "subscriptions",
    "support_access_grants",
    "users",
)

# Maintaining `updated_at` in a trigger rather than in the ORM means a row
# touched by a migration, a backfill job or a hand-run UPDATE is still stamped
# correctly. `now()` is the TRANSACTION timestamp, which is the right
# semantics: rows changed together in one transaction changed at one moment.
SET_UPDATED_AT_FN = """
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""


def upgrade() -> None:
    # Extensions first: `citext` provides the case-insensitive email type,
    # `pgcrypto` provides gen_random_uuid(), and `postgis` provides every
    # geometry column. Creating them here rather than assuming them means a
    # fresh local database and a fresh Supabase project migrate identically.
    #
    # On Supabase these usually already exist; IF NOT EXISTS makes that fine.
    # If the role lacks permission to create them, the failure names the
    # extension, and docs/CONFIGURATION.md carries the SQL to run by hand.
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_entries',
    sa.Column('cache_key', sa.Text(), nullable=False),
    sa.Column('namespace', sa.Text(), nullable=False),
    sa.Column('value', sa.LargeBinary(), nullable=False),
    sa.Column('content_type', sa.Text(), server_default=sa.text("'application/json'"), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cache_entries')),
    sa.UniqueConstraint('cache_key', name=op.f('uq_cache_entries_cache_key'))
    )
    op.create_index('ix_cache_entries_expires_at', 'cache_entries', ['expires_at'], unique=False)
    op.create_index('ix_cache_entries_namespace', 'cache_entries', ['namespace'], unique=False)
    op.create_table('courses',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('place', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('distance_type', sa.Enum('Sprint', 'Olympic', '70.3', 'Full', name='distance_type'), nullable=False),
    sa.Column('difficulty', sa.Enum('APPROACHABLE', 'MODERATE', 'HARD', 'BRUTAL', name='difficulty'), nullable=False),
    sa.Column('elevation_gain_m', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('media_hero_path', sa.Text(), nullable=True),
    sa.Column('media_card_path', sa.Text(), nullable=True),
    sa.Column('tone_color', sa.String(length=9), nullable=True),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.Column('lat', sa.Numeric(), nullable=False),
    sa.Column('lng', sa.Numeric(), nullable=False),
    sa.Column('is_fictional', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('lat BETWEEN -90 AND 90', name=op.f('ck_courses_courses_lat_range')),
    sa.CheckConstraint('lng BETWEEN -180 AND 180', name=op.f('ck_courses_courses_lng_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_courses')),
    sa.UniqueConstraint('slug', name=op.f('uq_courses_slug'))
    )
    op.create_index('ix_courses_distance_type', 'courses', ['distance_type'], unique=False)
    op.create_table('incidents',
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.Enum('SEV-1', 'SEV-2', 'SEV-3', 'SEV-4', name='incident_severity'), nullable=False),
    sa.Column('what', sa.Text(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('service_ref', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    op.create_index('ix_incidents_occurred_at', 'incidents', [sa.text('occurred_at DESC')], unique=False)
    op.create_table('job_runs',
    sa.Column('job_name', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=True),
    sa.Column('items_processed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_runs'))
    )
    op.create_index('ix_job_runs_job_name_started_at', 'job_runs', ['job_name', sa.text('started_at DESC')], unique=False)
    op.create_table('kpi_snapshots',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('plans_solved', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('free_to_paid_pct', sa.Numeric(), nullable=True),
    sa.Column('solver_p50_ms', sa.Integer(), nullable=True),
    sa.Column('solver_p95_ms', sa.Integer(), nullable=True),
    sa.Column('solver_p99_ms', sa.Integer(), nullable=True),
    sa.Column('support_ticket_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_accounts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('paying_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('season_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('coach_seat_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kpi_snapshots')),
    sa.UniqueConstraint('date', name=op.f('uq_kpi_snapshots_date'))
    )
    op.create_table('price_catalog',
    sa.Column('tier', sa.Enum('free', 'per_race', 'season', 'coach', name='user_tier'), nullable=False),
    sa.Column('currency', sa.Enum('GBP', 'USD', 'EUR', name='currency'), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('provider_price_id', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_cents >= 0', name=op.f('ck_price_catalog_price_catalog_amount_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_catalog')),
    sa.UniqueConstraint('tier', 'currency', name='uq_price_catalog_tier_currency')
    )
    op.create_table('rate_limit_counters',
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('bucket', sa.Text(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rate_limit_counters')),
    sa.UniqueConstraint('subject', 'bucket', 'window_start', name='uq_rate_limit_counters_subject_bucket_window')
    )
    op.create_index('ix_rate_limit_counters_window_start', 'rate_limit_counters', ['window_start'], unique=False)
    op.create_table('service_health',
    sa.Column('service_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('nominal', 'degraded', 'down', name='service_status'), server_default=sa.text("'nominal'"), nullable=False),
    sa.Column('uptime_pct_30d', sa.Numeric(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_health')),
    sa.UniqueConstraint('service_name', name=op.f('uq_service_health_service_name'))
    )
    op.create_table('users',
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('emergency_contact_name', sa.Text(), nullable=True),
    sa.Column('emergency_contact_phone', sa.Text(), nullable=True),
    sa.Column('units', sa.Enum('metric', 'imperial', name='unit_system'), server_default=sa.text("'metric'"), nullable=False),
    sa.Column('level', sa.Enum('first', 'improver', 'experienced', name='athlete_level'), server_default=sa.text("'first'"), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('bike_position', sa.Enum('road_hoods', 'road_drops', 'road_clipons', 'tt_bike', name='bike_position_enum'), nullable=True),
    sa.Column('bike_helmet', sa.Enum('standard', 'aero', name='bike_helmet_enum'), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tier', sa.Enum('free', 'per_race', 'season', 'coach', name='user_tier'), server_default=sa.text("'free'"), nullable=False),
    sa.Column('is_coach', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('account_state', sa.Enum('active', 'dormant', 'erased', name='account_state'), server_default=sa.text("'active'"), nullable=False),
    sa.Column('currency', sa.Enum('GBP', 'USD', 'EUR', name='currency'), server_default=sa.text("'GBP'"), nullable=False),
    sa.Column('sessions_invalidated_before', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('failed_login_count >= 0', name=op.f('ck_users_users_failed_login_count_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index('ix_users_account_state', 'users', ['account_state'], unique=False)
    op.create_index('ix_users_last_seen_at', 'users', ['last_seen_at'], unique=False, postgresql_using='btree')
    op.create_index('ix_users_tier', 'users', ['tier'], unique=False)
    op.create_table('admin_role_audit',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('support', 'ops', 'admin', name='admin_role'), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_admin_role_audit_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_admin_role_audit_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_role_audit'))
    )
    op.create_table('admin_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('support', 'ops', 'admin', name='admin_role'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_admin_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_roles')),
    sa.UniqueConstraint('user_id', 'role', name='uq_admin_roles_user_id_role')
    )
    op.create_table('audit_log',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('request_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_log_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_log_actor_user_id', 'audit_log', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_table('coach_athlete_links',
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'revoked', name='coach_link_status'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('perm_plans', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('perm_build', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('perm_analysis', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invite_token_hash', sa.Text(), nullable=True),
    sa.Column('invite_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invite_delivery_link', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('coach_id <> athlete_id', name=op.f('ck_coach_athlete_links_coach_athlete_links_not_self')),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], name=op.f('fk_coach_athlete_links_athlete_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], name=op.f('fk_coach_athlete_links_coach_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coach_athlete_links')),
    sa.UniqueConstraint('coach_id', 'athlete_id', name='uq_coach_athlete_links_coach_athlete'),
    sa.UniqueConstraint('invite_token_hash', name=op.f('uq_coach_athlete_links_invite_token_hash'))
    )
    op.create_index('ix_coach_athlete_links_athlete_id_status', 'coach_athlete_links', ['athlete_id', 'status'], unique=False)
    op.create_index('ix_coach_athlete_links_coach_id_status', 'coach_athlete_links', ['coach_id', 'status'], unique=False)
    op.create_table('coach_notes',
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], name=op.f('fk_coach_notes_athlete_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], name=op.f('fk_coach_notes_coach_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_coach_notes'))
    )
    op.create_index('ix_coach_notes_athlete_id', 'coach_notes', ['athlete_id'], unique=False)
    op.create_table('constraint_history',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('measured', 'tested', 'manual', 'estimated', name='constraint_source'), nullable=False),
    sa.Column('source_detail', sa.Text(), nullable=True),
    sa.Column('confidence_pct', sa.Integer(), nullable=True),
    sa.Column('evidence_note', sa.Text(), nullable=True),
    sa.Column('tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('measured_at_temp_c', sa.Numeric(), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('changed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], name=op.f('fk_constraint_history_changed_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_constraint_history_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_constraint_history'))
    )
    op.create_index('ix_constraint_history_user_id_key', 'constraint_history', ['user_id', 'key'], unique=False)
    op.create_table('constraints',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('measured', 'tested', 'manual', 'estimated', name='constraint_source'), nullable=False),
    sa.Column('source_detail', sa.Text(), nullable=True),
    sa.Column('confidence_pct', sa.Integer(), nullable=True),
    sa.Column('evidence_note', sa.Text(), nullable=True),
    sa.Column('tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('measured_at_temp_c', sa.Numeric(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence_pct IS NULL OR (confidence_pct BETWEEN 0 AND 100)', name=op.f('ck_constraints_constraints_confidence_pct_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_constraints_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_constraints')),
    sa.UniqueConstraint('user_id', 'key', name='uq_constraints_user_id_key')
    )
    op.create_index('ix_constraints_user_id', 'constraints', ['user_id'], unique=False)
    op.create_table('course_bundles',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'superseded', name='bundle_status'), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('provenance', sa.Enum('OFFICIAL', 'CROWD', 'ESTIMATED', name='provenance'), server_default=sa.text("'ESTIMATED'"), nullable=False),
    sa.Column('verified_at', sa.Date(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('season_year', sa.Integer(), nullable=True),
    sa.Column('elevation_profile', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('barriers', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('aid_stations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('waypoints', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('elevation_source', sa.Text(), server_default=sa.text("'terrain'"), nullable=False),
    sa.Column('attribution', sa.Text(), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('plans_affected_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('bundle_asset_key', sa.Text(), nullable=True),
    sa.Column('terrain_pmtiles_key', sa.Text(), nullable=True),
    sa.Column('provenance_detail', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("elevation_source = 'terrain'", name=op.f('ck_course_bundles_course_bundles_elevation_source_terrain')),
    sa.CheckConstraint('jsonb_array_length(barriers) > 0', name=op.f('ck_course_bundles_course_bundles_barriers_present')),
    sa.CheckConstraint('length(attribution) > 0', name=op.f('ck_course_bundles_course_bundles_attribution_present')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_bundles_course_id_courses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_bundles')),
    sa.UniqueConstraint('course_id', 'version', name='uq_course_bundles_course_id_version')
    )
    op.create_index('ix_course_bundles_course_id_status', 'course_bundles', ['course_id', 'status'], unique=False)
    op.create_index('ix_course_bundles_segments_gin', 'course_bundles', ['segments'], unique=False, postgresql_using='gin', postgresql_ops={'segments': 'jsonb_path_ops'})
    op.create_table('crowd_reports',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('aid_station', 'cutoff', 'elevation', 'route', 'special_needs', 'water_temp', name='crowd_category'), nullable=False),
    sa.Column('upload_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('agreement_weight_pct', sa.Numeric(), server_default=sa.text('0'), nullable=False),
    sa.Column('confidence', sa.Enum('high', 'med', 'low', name='crowd_confidence'), server_default=sa.text("'low'"), nullable=False),
    sa.Column('affected_plans_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'promoted', 'held', 'rejected', name='crowd_status'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('agreement_weight_pct BETWEEN 0 AND 100', name=op.f('ck_crowd_reports_crowd_reports_agreement_pct_range')),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_crowd_reports_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_crowd_reports_resolved_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crowd_reports'))
    )
    op.create_index('ix_crowd_reports_course_id_status', 'crowd_reports', ['course_id', 'status'], unique=False)
    op.create_table('email_messages',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('to_address', sa.Text(), nullable=False),
    sa.Column('from_address', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('template_key', sa.Text(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('transport', sa.Text(), nullable=False),
    sa.Column('delivered', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('delivery_error', sa.Text(), nullable=True),
    sa.Column('provider_message_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_messages_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_messages'))
    )
    op.create_index('ix_email_messages_template_key', 'email_messages', ['template_key'], unique=False)
    op.create_index('ix_email_messages_user_id', 'email_messages', ['user_id'], unique=False)
    op.create_table('email_verification_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_link', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_verification_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_verification_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_email_verification_tokens_token_hash'))
    )
    op.create_index('ix_email_verification_tokens_user_id', 'email_verification_tokens', ['user_id'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('request_hash', sa.Text(), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_idempotency_keys_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_keys')),
    sa.UniqueConstraint('key', name=op.f('uq_idempotency_keys_key'))
    )
    op.create_index('ix_idempotency_keys_expires_at', 'idempotency_keys', ['expires_at'], unique=False)
    op.create_table('invoices',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('invoice_number', sa.Text(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.Enum('GBP', 'USD', 'EUR', name='currency'), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payment_provider_invoice_id', sa.Text(), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_invoices_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('invoice_number', name=op.f('uq_invoices_invoice_number'))
    )
    op.create_index('ix_invoices_user_id_issued_at', 'invoices', ['user_id', 'issued_at'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type_key', sa.Enum('drift', 'week', 'cutoff', 'bundle', 'analysis', 'digest', name='notification_type'), nullable=False),
    sa.Column('channel_email', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('channel_push', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('channel_inapp', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('drift_sensitivity', sa.Enum('everything', 'balanced', 'critical', name='drift_sensitivity'), server_default=sa.text("'balanced'"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_preferences')),
    sa.UniqueConstraint('user_id', 'type_key', name='uq_notification_preferences_user_type')
    )
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_link', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_password_reset_tokens_token_hash'))
    )
    op.create_index('ix_password_reset_tokens_user_id', 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh_key', sa.Text(), nullable=False),
    sa.Column('auth_key', sa.Text(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_push_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_subscriptions')),
    sa.UniqueConstraint('endpoint', name=op.f('uq_push_subscriptions_endpoint'))
    )
    op.create_index('ix_push_subscriptions_user_id', 'push_subscriptions', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.Text(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('rotated_to_session_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rotated_to_session_id'], ['sessions.id'], name=op.f('fk_sessions_rotated_to_session_id_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('refresh_token_hash', name=op.f('uq_sessions_refresh_token_hash'))
    )
    op.create_index('ix_sessions_expires_at', 'sessions', ['expires_at'], unique=False)
    op.create_index('ix_sessions_user_id', 'sessions', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.Enum('free', 'per_race', 'season', 'coach', name='user_tier'), nullable=False),
    sa.Column('status', sa.Enum('active', 'cancelled', 'past_due', name='subscription_status'), nullable=False),
    sa.Column('renews_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_provider_customer_id', sa.Text(), nullable=True),
    sa.Column('payment_provider_subscription_id', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('payment_provider_subscription_id', name=op.f('uq_subscriptions_payment_provider_subscription_id'))
    )
    op.create_index('ix_subscriptions_user_id_status', 'subscriptions', ['user_id', 'status'], unique=False)
    op.create_table('support_access_grants',
    sa.Column('athlete_id', sa.UUID(), nullable=False),
    sa.Column('support_agent_id', sa.UUID(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('denied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accessed_log', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('granted_at IS NULL OR expires_at IS NOT NULL', name=op.f('ck_support_access_grants_support_access_grants_granted_has_expiry')),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], name=op.f('fk_support_access_grants_athlete_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['support_agent_id'], ['users.id'], name=op.f('fk_support_access_grants_support_agent_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_access_grants'))
    )
    op.create_index('ix_support_access_grants_athlete_id', 'support_access_grants', ['athlete_id'], unique=False)
    op.create_index('ix_support_access_grants_expires_at', 'support_access_grants', ['expires_at'], unique=False)
    op.create_table('course_bundle_diffs',
    sa.Column('from_bundle_id', sa.UUID(), nullable=False),
    sa.Column('to_bundle_id', sa.UUID(), nullable=False),
    sa.Column('field_deltas', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['from_bundle_id'], ['course_bundles.id'], name=op.f('fk_course_bundle_diffs_from_bundle_id_course_bundles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_bundle_id'], ['course_bundles.id'], name=op.f('fk_course_bundle_diffs_to_bundle_id_course_bundles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_bundle_diffs')),
    sa.UniqueConstraint('from_bundle_id', 'to_bundle_id', name='uq_course_bundle_diffs_from_to')
    )
    op.create_table('course_bundle_legs',
    sa.Column('bundle_id', sa.UUID(), nullable=False),
    sa.Column('leg', sa.Enum('SWIM', 'BIKE', 'RUN', name='leg'), nullable=False),
    sa.Column('geometry', Geometry(geometry_type='LINESTRINGZ', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('distance_m', sa.Numeric(), nullable=False),
    sa.Column('elevation_gain_m', sa.Numeric(), server_default=sa.text('0'), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('surface_quality', sa.Enum('smooth_asphalt', 'typical_road', 'rough_chipseal', name='surface_quality'), server_default=sa.text("'typical_road'"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('distance_m > 0', name=op.f('ck_course_bundle_legs_course_bundle_legs_distance_positive')),
    sa.CheckConstraint('node_count > 1', name=op.f('ck_course_bundle_legs_course_bundle_legs_node_count_min')),
    sa.ForeignKeyConstraint(['bundle_id'], ['course_bundles.id'], name=op.f('fk_course_bundle_legs_bundle_id_course_bundles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_bundle_legs')),
    sa.UniqueConstraint('bundle_id', 'leg', name='uq_course_bundle_legs_bundle_id_leg')
    )
    op.create_index('ix_course_bundle_legs_geometry', 'course_bundle_legs', ['geometry'], unique=False, postgresql_using='gist')
    op.create_table('crowd_report_uploads',
    sa.Column('crowd_report_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['crowd_report_id'], ['crowd_reports.id'], name=op.f('fk_crowd_report_uploads_crowd_report_id_crowd_reports'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_crowd_report_uploads_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crowd_report_uploads')),
    sa.UniqueConstraint('crowd_report_id', 'user_id', name='uq_crowd_report_uploads_report_user')
    )
    op.create_table('races',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('course_bundle_id', sa.UUID(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('start_time_local', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('upcoming', 'cancelled', 'deferred', 'completed', name='race_status'), server_default=sa.text("'upcoming'"), nullable=False),
    sa.Column('bib', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_bundle_id'], ['course_bundles.id'], name=op.f('fk_races_course_bundle_id_course_bundles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_races_course_id_courses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_races_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_races'))
    )
    op.create_index('ix_races_course_bundle_id', 'races', ['course_bundle_id'], unique=False)
    op.create_index('ix_races_event_date', 'races', ['event_date'], unique=False)
    op.create_index('ix_races_user_id_status', 'races', ['user_id', 'status'], unique=False)
    op.create_table('refunds',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Enum('race_cancelled', 'bundle_error', 'other', name='refund_reason'), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('provider_refund_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('amount_cents > 0', name=op.f('ck_refunds_refunds_amount_positive')),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_refunds_actor_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_refunds_invoice_id_invoices'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refunds')),
    sa.UniqueConstraint('provider_refund_id', name=op.f('uq_refunds_provider_refund_id'))
    )
    op.create_index('ix_refunds_invoice_id', 'refunds', ['invoice_id'], unique=False)
    op.create_table('plans',
    sa.Column('race_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'past', 'pending_athlete_approval', name='plan_status'), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('goal_minutes', sa.Numeric(), nullable=True),
    sa.Column('projected_minutes', sa.Numeric(), nullable=True),
    sa.Column('feasibility', sa.Enum('CLEAR', 'TIGHT', 'STALE', 'NOT_SOLVED', name='feasibility'), server_default=sa.text("'NOT_SOLVED'"), nullable=False),
    sa.Column('worst_margin_minutes', sa.Numeric(), nullable=True),
    sa.Column('binding_constraint_key', sa.Text(), nullable=True),
    sa.Column('solved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('solve_input_hash', sa.Text(), nullable=True),
    sa.Column('constraints_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('forecast_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('assumed_fields', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('readiness_fraction', sa.Numeric(), nullable=True),
    sa.Column('readiness_note', sa.Text(), nullable=True),
    sa.Column('shared', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('race_card_pdf_url', sa.Text(), nullable=True),
    sa.Column('built_by_coach_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('superseded_by_plan_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('version >= 1', name=op.f('ck_plans_plans_version_positive')),
    sa.ForeignKeyConstraint(['built_by_coach_id'], ['users.id'], name=op.f('fk_plans_built_by_coach_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], name=op.f('fk_plans_race_id_races'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['superseded_by_plan_id'], ['plans.id'], name=op.f('fk_plans_superseded_by_plan_id_plans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_plans_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans')),
    sa.UniqueConstraint('race_id', 'version', name='uq_plans_race_id_version')
    )
    op.create_index('ix_plans_race_id_version', 'plans', ['race_id', sa.text('version DESC')], unique=False)
    op.create_index('ix_plans_solve_input_hash', 'plans', ['solve_input_hash'], unique=False)
    op.create_index('ix_plans_user_id_status', 'plans', ['user_id', 'status'], unique=False)
    op.create_index('uq_plans_one_active_per_race', 'plans', ['race_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('funnel_events',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('course_id', sa.UUID(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_funnel_events_course_id_courses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_funnel_events_plan_id_plans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_funnel_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_funnel_events'))
    )
    op.create_index('ix_funnel_events_event_type_occurred_at', 'funnel_events', ['event_type', 'occurred_at'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type_key', sa.Enum('drift', 'week', 'cutoff', 'bundle', 'analysis', 'digest', name='notification_type'), nullable=False),
    sa.Column('tag', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('info', 'ok', 'warn', 'bad', name='notification_severity'), nullable=False),
    sa.Column('race_id', sa.UUID(), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('deltas', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('cta_label', sa.Text(), nullable=True),
    sa.Column('cta_href', sa.Text(), nullable=True),
    sa.Column('read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_notifications_plan_id_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], name=op.f('fk_notifications_race_id_races'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_user_id_created_at', 'notifications', ['user_id', sa.text('created_at DESC')], unique=False)
    op.create_index('ix_notifications_user_id_unread', 'notifications', ['user_id'], unique=False, postgresql_where=sa.text('read = false'))
    op.create_table('override_events',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('constraint_key', sa.Text(), nullable=False),
    sa.Column('overridden_from', sa.Numeric(), nullable=False),
    sa.Column('overridden_to', sa.Numeric(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_override_events_plan_id_plans'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_override_events_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_override_events'))
    )
    op.create_index('ix_override_events_plan_id', 'override_events', ['plan_id'], unique=False)
    op.create_table('plan_aid_actions',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('at_clock_minutes', sa.Numeric(), nullable=False),
    sa.Column('at_km', sa.Numeric(), nullable=False),
    sa.Column('leg', sa.Enum('SWIM', 'BIKE', 'RUN', name='leg'), nullable=False),
    sa.Column('station_name', sa.Text(), nullable=False),
    sa.Column('action_text', sa.Text(), nullable=False),
    sa.Column('cumulative_carb_g', sa.Numeric(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_plan_aid_actions_plan_id_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_aid_actions')),
    sa.UniqueConstraint('plan_id', 'ordinal', name='uq_plan_aid_actions_plan_id_ordinal')
    )
    op.create_index('ix_plan_aid_actions_plan_id', 'plan_aid_actions', ['plan_id'], unique=False)
    op.create_table('plan_bags',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.Enum('morning', 'bike_t1', 'run_t2', 'bike_sn', 'run_sn', name='bag_key'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('when_label', sa.Text(), nullable=False),
    sa.Column('item_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('item_count >= 0', name=op.f('ck_plan_bags_plan_bags_item_count_non_negative')),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_plan_bags_plan_id_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_bags')),
    sa.UniqueConstraint('plan_id', 'key', name='uq_plan_bags_plan_id_key')
    )
    op.create_table('plan_constraint_refs',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('source_label', sa.Text(), nullable=False),
    sa.Column('binding', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('affects_text', sa.Text(), nullable=True),
    sa.Column('override_text', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_plan_constraint_refs_plan_id_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_constraint_refs')),
    sa.UniqueConstraint('plan_id', 'key', name='uq_plan_constraint_refs_plan_id_key')
    )
    op.create_table('plan_drift_events',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cause', sa.Enum('forecast', 'constraint_change', 'course_bundle_change', name='drift_cause'), nullable=False),
    sa.Column('severity', sa.Enum('normal', 'cutoff_risk', name='drift_severity'), server_default=sa.text("'normal'"), nullable=False),
    sa.Column('field_deltas', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('status', sa.Enum('pending', 'applied', 'dismissed', name='drift_status'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resulting_plan_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_plan_drift_events_plan_id_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resulting_plan_id'], ['plans.id'], name=op.f('fk_plan_drift_events_resulting_plan_id_plans'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_drift_events'))
    )
    op.create_index('ix_plan_drift_events_plan_id_status', 'plan_drift_events', ['plan_id', 'status'], unique=False)
    op.create_table('plan_fuelling',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('carb_g_per_hr', sa.Integer(), nullable=False),
    sa.Column('fluid_ml_per_hr', sa.Integer(), nullable=False),
    sa.Column('sodium_mg_per_hr', sa.Integer(), nullable=False),
    sa.Column('caffeine_mg_total', sa.Integer(), nullable=False),
    sa.Column('total_carb_g', sa.Integer(), nullable=False),
    sa.Column('overridden', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('requires_multiple_transportable', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('binding_carb_key', sa.Text(), nullable=True),
    sa.Column('binding_fluid_key', sa.Text(), nullable=True),
    sa.Column('binding_sodium_key', sa.Text(), nullable=True),
    sa.Column('binding_caffeine_key', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_plan_fuelling_plan_id_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_fuelling')),
    sa.UniqueConstraint('plan_id', name=op.f('uq_plan_fuelling_plan_id'))
    )
    op.create_table('plan_gates',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('leg', sa.Enum('SWIM', 'BIKE', 'RUN', name='leg'), nullable=False),
    sa.Column('limit_minutes', sa.Numeric(), nullable=False),
    sa.Column('eta_minutes', sa.Numeric(), nullable=False),
    sa.Column('margin_minutes', sa.Numeric(), nullable=False),
    sa.Column('load_pct', sa.Numeric(), nullable=False),
    sa.Column('state', sa.Enum('clear', 'tight', 'bad', name='margin_state'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_plan_gates_plan_id_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_gates')),
    sa.UniqueConstraint('plan_id', 'name', name='uq_plan_gates_plan_id_name')
    )
    op.create_index('ix_plan_gates_plan_id', 'plan_gates', ['plan_id'], unique=False)
    op.create_table('plan_segments',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('leg', sa.Enum('SWIM', 'BIKE', 'RUN', name='leg'), nullable=False),
    sa.Column('from_km', sa.Numeric(), nullable=False),
    sa.Column('to_km', sa.Numeric(), nullable=False),
    sa.Column('terrain_desc', sa.Text(), nullable=True),
    sa.Column('target_watts', sa.Integer(), nullable=True),
    sa.Column('target_pace_sec_per_km', sa.Integer(), nullable=True),
    sa.Column('target_minutes', sa.Numeric(), nullable=False),
    sa.Column('hr_zone', sa.Text(), nullable=True),
    sa.Column('zone_width_pct', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('target_minutes > 0', name=op.f('ck_plan_segments_plan_segments_target_minutes_positive')),
    sa.CheckConstraint('to_km > from_km', name=op.f('ck_plan_segments_plan_segments_km_ordered')),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_plan_segments_plan_id_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_segments')),
    sa.UniqueConstraint('plan_id', 'ordinal', name='uq_plan_segments_plan_id_ordinal')
    )
    op.create_index('ix_plan_segments_plan_id', 'plan_segments', ['plan_id'], unique=False)
    op.create_table('plan_splits',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('leg', sa.Enum('SWIM', 'BIKE', 'RUN', name='leg'), nullable=False),
    sa.Column('distance', sa.Numeric(), nullable=False),
    sa.Column('target_pace_or_power', sa.Text(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('split_minutes', sa.Numeric(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('split_minutes > 0', name=op.f('ck_plan_splits_plan_splits_split_minutes_positive')),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_plan_splits_plan_id_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_splits')),
    sa.UniqueConstraint('plan_id', 'leg', name='uq_plan_splits_plan_id_leg')
    )
    op.create_table('post_race_files',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('format', sa.Enum('fit', 'gpx', 'tcx', name='race_file_format'), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processed', 'failed', name='race_file_status'), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('size_bytes > 0', name=op.f('ck_post_race_files_post_race_files_size_positive')),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_post_race_files_plan_id_plans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_post_race_files_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_race_files')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_post_race_files_storage_key'))
    )
    op.create_index('ix_post_race_files_status', 'post_race_files', ['status'], unique=False)
    op.create_index('ix_post_race_files_user_id', 'post_race_files', ['user_id'], unique=False)
    op.create_table('purchases',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('payment_provider_intent_id', sa.Text(), nullable=False),
    sa.Column('amount_cents', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.Enum('GBP', 'USD', 'EUR', name='currency'), nullable=False),
    sa.Column('status', sa.Enum('authorized', 'captured', 'voided', 'refunded', name='purchase_status'), nullable=False),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status <> 'captured' OR captured_at IS NOT NULL", name=op.f('ck_purchases_purchases_captured_has_timestamp')),
    sa.CheckConstraint('amount_cents >= 0', name=op.f('ck_purchases_purchases_amount_non_negative')),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_purchases_plan_id_plans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_purchases_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchases')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_purchases_idempotency_key')),
    sa.UniqueConstraint('payment_provider_intent_id', name=op.f('uq_purchases_payment_provider_intent_id'))
    )
    op.create_index('ix_purchases_status', 'purchases', ['status'], unique=False)
    op.create_index('ix_purchases_user_id', 'purchases', ['user_id'], unique=False)
    op.create_table('share_links',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('token_prefix', sa.String(length=12), nullable=False),
    sa.Column('scope', sa.Enum('full_plan', 'pacing_only', 'bags_only', 'race_card', name='share_scope'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('recipient_label', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_code_hash', sa.Text(), nullable=True),
    sa.Column('opens_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('opens_count >= 0', name=op.f('ck_share_links_share_links_opens_count_non_negative')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_share_links_created_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_share_links_plan_id_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_share_links')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_share_links_token_hash'))
    )
    op.create_index('ix_share_links_plan_id', 'share_links', ['plan_id'], unique=False)
    op.create_index('ix_share_links_token_prefix', 'share_links', ['token_prefix'], unique=False)
    op.create_table('solve_jobs',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', name='solve_job_status'), server_default=sa.text("'queued'"), nullable=False),
    sa.Column('solve_input_hash', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('resulting_plan_id', sa.UUID(), nullable=True),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('error_detail', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('request_id', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_solve_jobs_plan_id_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resulting_plan_id'], ['plans.id'], name=op.f('fk_solve_jobs_resulting_plan_id_plans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_solve_jobs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_solve_jobs'))
    )
    op.create_index('ix_solve_jobs_plan_id', 'solve_jobs', ['plan_id'], unique=False)
    op.create_index('ix_solve_jobs_user_id_status', 'solve_jobs', ['user_id', 'status'], unique=False)
    op.create_table('solve_timings',
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('total_ms', sa.Integer(), nullable=False),
    sa.Column('stage_timings_ms', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('exceeded_sla', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_solve_timings_plan_id_plans'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_solve_timings'))
    )
    op.create_index('ix_solve_timings_created_at', 'solve_timings', ['created_at'], unique=False)
    op.create_table('plan_bag_items',
    sa.Column('bag_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('qty', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('reason_constraint_key', sa.Text(), nullable=True),
    sa.Column('reason_text', sa.Text(), nullable=True),
    sa.Column('is_user_added', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('reason_constraint_key IS NOT NULL OR is_user_added = true', name=op.f('ck_plan_bag_items_plan_bag_items_generated_item_has_reason')),
    sa.ForeignKeyConstraint(['bag_id'], ['plan_bags.id'], name=op.f('fk_plan_bag_items_bag_id_plan_bags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_bag_items')),
    sa.UniqueConstraint('bag_id', 'ordinal', name='uq_plan_bag_items_bag_id_ordinal')
    )
    op.create_table('post_race_analyses',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('plan_version', sa.Integer(), nullable=False),
    sa.Column('race_file_id', sa.UUID(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_post_race_analyses_plan_id_plans'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['race_file_id'], ['post_race_files.id'], name=op.f('fk_post_race_analyses_race_file_id_post_race_files'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_race_analyses')),
    sa.UniqueConstraint('plan_id', 'race_file_id', name='uq_post_race_analyses_plan_file')
    )
    op.create_index('ix_post_race_analyses_plan_id', 'post_race_analyses', ['plan_id'], unique=False)
    op.create_table('share_link_opens',
    sa.Column('share_link_id', sa.UUID(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['share_link_id'], ['share_links.id'], name=op.f('fk_share_link_opens_share_link_id_share_links'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_share_link_opens'))
    )
    op.create_index('ix_share_link_opens_share_link_id', 'share_link_opens', ['share_link_id'], unique=False)
    op.create_table('analysis_actions',
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('projected_gain_minutes', sa.Numeric(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('how_to', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['post_race_analyses.id'], name=op.f('fk_analysis_actions_analysis_id_post_race_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_actions')),
    sa.UniqueConstraint('analysis_id', 'rank', name='uq_analysis_actions_analysis_id_rank')
    )
    op.create_table('analysis_calibrations',
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('constraint_key', sa.Text(), nullable=False),
    sa.Column('was', sa.Numeric(), nullable=False),
    sa.Column('now', sa.Numeric(), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('applied', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['post_race_analyses.id'], name=op.f('fk_analysis_calibrations_analysis_id_post_race_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_calibrations')),
    sa.UniqueConstraint('analysis_id', 'constraint_key', name='uq_analysis_calibrations_key')
    )
    op.create_table('analysis_compare_rows',
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('planned', sa.Text(), nullable=False),
    sa.Column('actual', sa.Text(), nullable=False),
    sa.Column('delta', sa.Text(), nullable=False),
    sa.Column('state', sa.Enum('good', 'ok', 'warn', 'bad', name='compare_state'), nullable=False),
    sa.Column('why', sa.Text(), nullable=True),
    sa.Column('drift_pct', sa.Numeric(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['post_race_analyses.id'], name=op.f('fk_analysis_compare_rows_analysis_id_post_race_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_compare_rows')),
    sa.UniqueConstraint('analysis_id', 'ordinal', name='uq_analysis_compare_rows_ordinal')
    )
    # ### end Alembic commands ###


    op.execute(SET_UPDATED_AT_FN)
    for table_name in UPDATED_AT_TABLES:
        op.execute(
            f"CREATE TRIGGER trg_{table_name}_set_updated_at "
            f"BEFORE UPDATE ON {table_name} "
            f"FOR EACH ROW EXECUTE FUNCTION set_updated_at()"
        )


def downgrade() -> None:
    for table_name in UPDATED_AT_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table_name}_set_updated_at ON {table_name}")
    op.execute("DROP FUNCTION IF EXISTS set_updated_at()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_compare_rows')
    op.drop_table('analysis_calibrations')
    op.drop_table('analysis_actions')
    op.drop_index('ix_share_link_opens_share_link_id', table_name='share_link_opens')
    op.drop_table('share_link_opens')
    op.drop_index('ix_post_race_analyses_plan_id', table_name='post_race_analyses')
    op.drop_table('post_race_analyses')
    op.drop_table('plan_bag_items')
    op.drop_index('ix_solve_timings_created_at', table_name='solve_timings')
    op.drop_table('solve_timings')
    op.drop_index('ix_solve_jobs_user_id_status', table_name='solve_jobs')
    op.drop_index('ix_solve_jobs_plan_id', table_name='solve_jobs')
    op.drop_table('solve_jobs')
    op.drop_index('ix_share_links_token_prefix', table_name='share_links')
    op.drop_index('ix_share_links_plan_id', table_name='share_links')
    op.drop_table('share_links')
    op.drop_index('ix_purchases_user_id', table_name='purchases')
    op.drop_index('ix_purchases_status', table_name='purchases')
    op.drop_table('purchases')
    op.drop_index('ix_post_race_files_user_id', table_name='post_race_files')
    op.drop_index('ix_post_race_files_status', table_name='post_race_files')
    op.drop_table('post_race_files')
    op.drop_table('plan_splits')
    op.drop_index('ix_plan_segments_plan_id', table_name='plan_segments')
    op.drop_table('plan_segments')
    op.drop_index('ix_plan_gates_plan_id', table_name='plan_gates')
    op.drop_table('plan_gates')
    op.drop_table('plan_fuelling')
    op.drop_index('ix_plan_drift_events_plan_id_status', table_name='plan_drift_events')
    op.drop_table('plan_drift_events')
    op.drop_table('plan_constraint_refs')
    op.drop_table('plan_bags')
    op.drop_index('ix_plan_aid_actions_plan_id', table_name='plan_aid_actions')
    op.drop_table('plan_aid_actions')
    op.drop_index('ix_override_events_plan_id', table_name='override_events')
    op.drop_table('override_events')
    op.drop_index('ix_notifications_user_id_unread', table_name='notifications', postgresql_where=sa.text('read = false'))
    op.drop_index('ix_notifications_user_id_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_funnel_events_event_type_occurred_at', table_name='funnel_events')
    op.drop_table('funnel_events')
    op.drop_index('uq_plans_one_active_per_race', table_name='plans', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('ix_plans_user_id_status', table_name='plans')
    op.drop_index('ix_plans_solve_input_hash', table_name='plans')
    op.drop_index('ix_plans_race_id_version', table_name='plans')
    op.drop_table('plans')
    op.drop_index('ix_refunds_invoice_id', table_name='refunds')
    op.drop_table('refunds')
    op.drop_index('ix_races_user_id_status', table_name='races')
    op.drop_index('ix_races_event_date', table_name='races')
    op.drop_index('ix_races_course_bundle_id', table_name='races')
    op.drop_table('races')
    op.drop_table('crowd_report_uploads')
    op.drop_index('ix_course_bundle_legs_geometry', table_name='course_bundle_legs', postgresql_using='gist')
    op.drop_table('course_bundle_legs')
    op.drop_table('course_bundle_diffs')
    op.drop_index('ix_support_access_grants_expires_at', table_name='support_access_grants')
    op.drop_index('ix_support_access_grants_athlete_id', table_name='support_access_grants')
    op.drop_table('support_access_grants')
    op.drop_index('ix_subscriptions_user_id_status', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_sessions_user_id', table_name='sessions')
    op.drop_index('ix_sessions_expires_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_push_subscriptions_user_id', table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index('ix_password_reset_tokens_user_id', table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_table('notification_preferences')
    op.drop_index('ix_invoices_user_id_issued_at', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('ix_idempotency_keys_expires_at', table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index('ix_email_verification_tokens_user_id', table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index('ix_email_messages_user_id', table_name='email_messages')
    op.drop_index('ix_email_messages_template_key', table_name='email_messages')
    op.drop_table('email_messages')
    op.drop_index('ix_crowd_reports_course_id_status', table_name='crowd_reports')
    op.drop_table('crowd_reports')
    op.drop_index('ix_course_bundles_segments_gin', table_name='course_bundles', postgresql_using='gin', postgresql_ops={'segments': 'jsonb_path_ops'})
    op.drop_index('ix_course_bundles_course_id_status', table_name='course_bundles')
    op.drop_table('course_bundles')
    op.drop_index('ix_constraints_user_id', table_name='constraints')
    op.drop_table('constraints')
    op.drop_index('ix_constraint_history_user_id_key', table_name='constraint_history')
    op.drop_table('constraint_history')
    op.drop_index('ix_coach_notes_athlete_id', table_name='coach_notes')
    op.drop_table('coach_notes')
    op.drop_index('ix_coach_athlete_links_coach_id_status', table_name='coach_athlete_links')
    op.drop_index('ix_coach_athlete_links_athlete_id_status', table_name='coach_athlete_links')
    op.drop_table('coach_athlete_links')
    op.drop_index('ix_audit_log_entity', table_name='audit_log')
    op.drop_index('ix_audit_log_actor_user_id', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('admin_roles')
    op.drop_table('admin_role_audit')
    op.drop_index('ix_users_tier', table_name='users')
    op.drop_index('ix_users_last_seen_at', table_name='users', postgresql_using='btree')
    op.drop_index('ix_users_account_state', table_name='users')
    op.drop_table('users')
    op.drop_table('service_health')
    op.drop_index('ix_rate_limit_counters_window_start', table_name='rate_limit_counters')
    op.drop_table('rate_limit_counters')
    op.drop_table('price_catalog')
    op.drop_table('kpi_snapshots')
    op.drop_index('ix_job_runs_job_name_started_at', table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_index('ix_incidents_occurred_at', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('ix_courses_distance_type', table_name='courses')
    op.drop_table('courses')
    op.drop_index('ix_cache_entries_namespace', table_name='cache_entries')
    op.drop_index('ix_cache_entries_expires_at', table_name='cache_entries')
    op.drop_table('cache_entries')
    # ### end Alembic commands ###

    for enum_name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
