"""Declarative base, shared column types and mixins.

Conventions applied to every table unless stated otherwise (Build Spec Part 4):
a ``uuid`` primary key defaulted by the database, and ``created_at`` /
``updated_at`` as ``timestamptz``. ``updated_at`` is maintained by a trigger
rather than by the ORM, so a row touched by a migration or by hand is still
stamped correctly — an application-level default is silently wrong exactly
when you most want the timestamp to be right.

All money is in minor units. All durations that feed the solver are numeric
**minutes**, formatted to ``H:MM`` only at the API boundary
(``BACKENDREQUIREMENTS.md`` §4).
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, MetaData, func, text
from sqlalchemy import Enum as SAEnum
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

#: Explicit naming so autogenerated migrations produce stable, reviewable
#: names instead of database-assigned ones that differ between environments.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def pg_enum(enum_cls: type[Any], name: str) -> SAEnum:
    """A native PostgreSQL enum whose labels are the enum's *values*.

    ``values_callable`` matters: without it SQLAlchemy stores member *names*
    (``FULL``) rather than values (``Full``), which would silently diverge
    from what the frontend sends and from ``SOLVER_MODEL.md``'s vocabulary.
    """
    return SAEnum(
        enum_cls,
        name=name,
        values_callable=lambda cls: [member.value for member in cls],
        native_enum=True,
        create_constraint=False,
        validate_strings=True,
    )


class UUIDPrimaryKey:
    """``id uuid primary key default gen_random_uuid()``."""

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


class Timestamps:
    """``created_at`` and ``updated_at``, both database-maintained."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        server_onupdate=func.now(),
    )


class Entity(Base, UUIDPrimaryKey, Timestamps):
    """Base for ordinary tables: uuid key plus both timestamps."""

    __abstract__ = True


class CreatedOnly(Base, UUIDPrimaryKey):
    """Base for append-only tables, which have no meaningful ``updated_at``.

    Used by history and audit tables, where an ``updated_at`` column would
    imply rows can be edited. They cannot: that is the point of them.
    """

    __abstract__ = True

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


#: Shorthand for the JSONB columns the schema uses for frozen snapshots and
#: delta arrays. Snapshots are frozen copies, never live joins: a later
#: constraint edit must not retroactively change a solved plan's numbers.
Json = JSONB

#: Python types for the two JSONB shapes the schema uses. Spelled out rather
#: than left as bare `dict`/`list` so `mypy` can check the call sites, and so
#: a reader can tell an object column from an array column at a glance.
JsonObject = dict[str, Any]
JsonArray = list[Any]

__all__ = [
    "NAMING_CONVENTION",
    "Base",
    "CreatedOnly",
    "Entity",
    "Json",
    "JsonArray",
    "JsonObject",
    "Timestamps",
    "UUIDPrimaryKey",
    "pg_enum",
]
