"""Build the solver's golden course fixtures from SOLVER_MODEL.md §B.1.

These are SYNTHETIC and MUST STAY SO. They are the frozen inputs of the solver's
golden-file regression suite (`RaceOS_Build_Spec.md` Part 19.2), and they are
deliberately unrelated to the nine seeded bundles that
`pipelines/course-ingest` produces -- even though `C-TRAM` shares a name and
coordinates with Tramuntana Full.

The reason is a hard one. If a golden case read a pipeline-generated bundle,
regenerating a course would silently change the golden expectations, and the
solver's determinism guarantee would become a property of the routing engine
rather than of the solver. So: static files, checked in, generated by this
script and nothing else.

    python backend/tests/golden/build_golden_courses.py

This script imports nothing from `course_ingest`. That is deliberate and is
asserted by `pipelines/course-ingest/tests/test_golden_isolation.py`.
"""
from __future__ import annotations

import json
from pathlib import Path

OUT = Path(__file__).resolve().parent / "courses"
NODE_SPACING_M = 100.0  # SOLVER_MODEL.md B.1: "Elevation series: 100 m node spacing"


def leg_series(segments, start_h=0.0):
    """Node series (s, h) at 100 m spacing reproducing each segment's net
    gradient exactly, per SOLVER_MODEL.md B.1."""
    s = 0.0
    h = start_h
    nodes = [(0.0, h)]
    for seg in segments:
        length = seg["km"] * 1000.0
        steps = max(1, int(round(length / NODE_SPACING_M)))
        step = length / steps
        for _ in range(steps):
            h += seg["net_gradient"] * step
            s += step
            nodes.append((round(s, 3), round(h, 4)))
    return nodes


def shift_to_mean(nodes, target_mean):
    """Offset the whole series so its distance-weighted mean matches B.1."""
    total = nodes[-1][0]
    if total <= 0:
        return nodes
    weighted = sum(
        (nodes[i][1] + nodes[i + 1][1]) / 2.0 * (nodes[i + 1][0] - nodes[i][0])
        for i in range(len(nodes) - 1)
    )
    delta = target_mean - weighted / total
    return [(s, round(h + delta, 4)) for s, h in nodes]


def gain(nodes):
    return round(sum(max(0.0, nodes[i + 1][1] - nodes[i][1]) for i in range(len(nodes) - 1)), 1)


def lap_segments(lap_km, gradients, laps, name):
    """Equal-quarter lap pattern, repeated. B.1's run construction."""
    out = []
    quarter = lap_km / len(gradients)
    for lap in range(1, laps + 1):
        for i, g in enumerate(gradients, start=1):
            out.append({"name": f"{name} lap {lap} q{i}", "km": quarter, "net_gradient": g})
    return out


def scaled_lap_segments(total_km, laps, quarters, target_gain_m, name):
    """A symmetric lap profile scaled so total ascent is exactly `target_gain_m`.

    Used where B.1 states a run leg's aggregate gain but not its segments; this
    reproduces the document's number rather than inventing a different one.
    """
    lap_km = total_km / laps
    quarter_km = lap_km / quarters
    # Half the quarters climb, half descend, symmetric so the lap closes.
    ups = quarters // 2
    per_lap_gain = target_gain_m / laps
    g_up = per_lap_gain / (ups * quarter_km * 1000.0)
    pattern = [g_up if i < ups else -g_up for i in range(quarters)]
    return lap_segments(lap_km, pattern, laps, name)


C_TRAM_BIKE = [
    {"name": "Coastal out", "km": 24.0, "net_gradient": 0.002},
    {"name": "Sa Pobla flats", "km": 18.0, "net_gradient": 0.004},
    {"name": "Femenia approach", "km": 9.6, "net_gradient": 0.018},
    {"name": "Coll de Femenia", "km": 8.4, "net_gradient": 0.058},
    {"name": "Femenia descent", "km": 7.2, "net_gradient": -0.055},
    {"name": "Orient valley", "km": 21.0, "net_gradient": 0.010},
    {"name": "Coll d'Honor", "km": 5.8, "net_gradient": 0.049},
    {"name": "Honor descent", "km": 6.4, "net_gradient": -0.048},
    {"name": "Inland rollers", "km": 26.0, "net_gradient": 0.006},
    {"name": "Sencelles flats", "km": 22.0, "net_gradient": 0.001},
    {"name": "Return coastal", "km": 22.0, "net_gradient": 0.003},
    {"name": "Alcudia run-in", "km": 9.8, "net_gradient": -0.006},
]

C_FLAT_BIKE = [
    {"name": f"Costa Plana {i + 1}", "km": 22.5, "net_gradient": g}
    for i, g in enumerate([0.001, -0.001, 0.002, -0.002, 0.001, -0.001, 0.002, -0.002])
]

C_ALTA_BIKE = [
    {"name": "Valley approach", "km": 28.0, "net_gradient": 0.004},
    {"name": "First pass", "km": 21.0, "net_gradient": 0.071},
    {"name": "First descent", "km": 18.0, "net_gradient": -0.062},
    {"name": "High plateau", "km": 34.0, "net_gradient": 0.008},
    {"name": "Second pass", "km": 26.0, "net_gradient": 0.065},
    {"name": "Long descent", "km": 49.0, "net_gradient": -0.031},
]


def truncate(segments, target_km):
    out = []
    remaining = target_km
    for seg in segments:
        if remaining <= 0:
            break
        take = min(seg["km"], remaining)
        out.append({**seg, "km": round(take, 4)})
        remaining -= take
    return out


def aid(leg, kms, contents):
    return [
        {"leg": leg, "name": f"{leg.title()} aid {i}", "km": km, "contents": contents,
         "provenance": "ESTIMATED"}
        for i, km in enumerate(kms, start=1)
    ]


def every(step, limit):
    out = []
    km = step
    while km <= limit + 1e-9:
        out.append(round(km, 3))
        km += step
    return out


BIKE_CONTENTS = ["water", "sports_drink", "banana", "energy_bar"]
RUN_CONTENTS = ["water", "sports_drink", "cola", "energy_gel"]


def build(course_id, name, distance_type, lat, lng, tz, swim_m, swim_kind,
          bike_segments, bike_surface, bike_mean, bike_declared_gain,
          run_segments, run_mean, run_declared_gain, barriers,
          bike_aid_km, run_aid_step):
    bike_nodes = shift_to_mean(leg_series(bike_segments), bike_mean)
    run_nodes = shift_to_mean(leg_series(run_segments), run_mean)
    bike_km = round(sum(s["km"] for s in bike_segments), 4)
    run_km = round(sum(s["km"] for s in run_segments), 4)

    def segs(seglist, leg):
        out = []
        cursor = 0.0
        for i, seg in enumerate(seglist, start=1):
            out.append({
                "ordinal": i, "leg": leg, "name": seg["name"],
                "from_km": round(cursor, 4), "to_km": round(cursor + seg["km"], 4),
                "net_gradient": seg["net_gradient"],
                "elevation_gain_m": round(max(0.0, seg["net_gradient"]) * seg["km"] * 1000.0, 2),
                "surface_quality": bike_surface if leg == "BIKE" else "typical_road",
                "name_source": "SYNTHETIC",
            })
            cursor += seg["km"]
        return out

    return {
        "golden_course_id": course_id,
        "synthetic": True,
        "source": "SOLVER_MODEL.md §B.1",
        "generated_by": "backend/tests/golden/build_golden_courses.py",
        "warning": (
            "Synthetic solver fixture. NOT produced by pipelines/course-ingest and never to be "
            "replaced by a pipeline-generated bundle: a golden case that read generated geometry "
            "would make the solver's determinism guarantee depend on the routing engine."
        ),
        "name": name,
        "distance_type": distance_type,
        "lat": lat, "lng": lng, "timezone": tz,
        "elevation_source": "terrain",
        "node_spacing_m": NODE_SPACING_M,
        "legs": {
            "SWIM": {"distance_m": swim_m, "water": swim_kind, "elevation_gain_m": 0.0,
                     "nodes": [[0.0, 0.0], [float(swim_m), 0.0]]},
            "BIKE": {"distance_m": round(bike_km * 1000.0, 1), "surface_quality": bike_surface,
                     "mean_elevation_m": bike_mean,
                     "elevation_gain_m": gain(bike_nodes),
                     "declared_elevation_gain_m": bike_declared_gain,
                     "nodes": [[s, h] for s, h in bike_nodes]},
            "RUN": {"distance_m": round(run_km * 1000.0, 1), "surface_quality": "typical_road",
                    "mean_elevation_m": run_mean,
                    "elevation_gain_m": gain(run_nodes),
                    "declared_elevation_gain_m": run_declared_gain,
                    "nodes": [[s, h] for s, h in run_nodes]},
        },
        "segments": segs(bike_segments, "BIKE") + segs(run_segments, "RUN"),
        "barriers": barriers,
        "aid_stations": aid("BIKE", bike_aid_km, BIKE_CONTENTS)
        + aid("RUN", every(run_aid_step, run_km - run_aid_step / 2), RUN_CONTENTS),
    }


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    tram_barriers = [
        {"name": "swim_exit", "leg": "SWIM", "limit_minutes_from_start": 140.0, "km": 3.8},
        {"name": "bike_km_120", "leg": "BIKE", "limit_minutes_from_start": 510.0, "km": 120.0},
        {"name": "bike_cutoff", "leg": "BIKE", "limit_minutes_from_start": 630.0, "km": 180.2},
        {"name": "finish", "leg": "RUN", "limit_minutes_from_start": 960.0, "km": 42.195},
    ]
    courses = [
        build("C-TRAM", "Serra de Tramuntana", "full", 39.85, 3.12, "Europe/Madrid",
              3800, "sea", C_TRAM_BIKE, "typical_road", 120.0, 2100,
              lap_segments(10.549, [0.004, -0.004, 0.003, -0.003], 4, "Tramuntana run"),
              25.0, 180, tram_barriers, [20, 45, 70, 95, 120, 145, 170], 2.1),
        build("C-FLAT", "Costa Plana", "full", 39.85, 3.12, "Europe/Madrid",
              3800, "sea", C_FLAT_BIKE, "smooth_asphalt", 15.0, 220,
              lap_segments(10.54875, [0.0, 0.0, 0.0, 0.0], 4, "Costa Plana run"),
              15.0, 0, tram_barriers, [20, 45, 70, 95, 120, 145, 170], 2.1),
        build("C-ALTA", "Alta Ruta", "full", 46.52, 7.98, "Europe/Zurich",
              3800, "lake", C_ALTA_BIKE, "typical_road", 980.0, 3900,
              scaled_lap_segments(42.195, 4, 4, 620.0, "Alta Ruta run"),
              640.0, 620,
              [
                  {"name": "swim_exit", "leg": "SWIM", "limit_minutes_from_start": 150.0, "km": 3.8},
                  {"name": "bike_cutoff", "leg": "BIKE", "limit_minutes_from_start": 690.0, "km": 176.0},
                  {"name": "finish", "leg": "RUN", "limit_minutes_from_start": 1020.0, "km": 42.195},
              ],
              [20, 45, 70, 95, 120, 145, 170], 2.1),
        build("C-HALF", "Tramuntana 70.3", "half", 39.85, 3.12, "Europe/Madrid",
              1900, "sea", truncate(C_TRAM_BIKE, 90.1), "typical_road", 120.0, 1050,
              lap_segments(10.55, [0.004, -0.004, 0.003, -0.003], 2, "Tramuntana 70.3 run"),
              25.0, 90,
              [
                  {"name": "swim_exit", "leg": "SWIM", "limit_minutes_from_start": 70.0, "km": 1.9},
                  {"name": "bike_cutoff", "leg": "BIKE", "limit_minutes_from_start": 330.0, "km": 90.1},
                  {"name": "finish", "leg": "RUN", "limit_minutes_from_start": 510.0, "km": 21.1},
              ],
              [20, 45, 70], 2.1),
        build("C-OLY", "Alcudia Olympic", "olympic", 39.85, 3.12, "Europe/Madrid",
              1500, "sea",
              [{"name": "Olympic out", "km": 20.0, "net_gradient": 0.002},
               {"name": "Olympic back", "km": 20.0, "net_gradient": -0.002}],
              "typical_road", 15.0, 80,
              [{"name": "Olympic run out", "km": 5.0, "net_gradient": 0.0},
               {"name": "Olympic run back", "km": 5.0, "net_gradient": 0.0}],
              15.0, 0,
              [
                  {"name": "swim_exit", "leg": "SWIM", "limit_minutes_from_start": 50.0, "km": 1.5},
                  {"name": "bike_cutoff", "leg": "BIKE", "limit_minutes_from_start": 170.0, "km": 40.0},
                  {"name": "finish", "leg": "RUN", "limit_minutes_from_start": 240.0, "km": 10.0},
              ],
              [20], 2.5),
        build("C-SPR", "Alcudia Sprint", "sprint", 39.85, 3.12, "Europe/Madrid",
              750, "sea",
              [{"name": "Sprint out", "km": 10.0, "net_gradient": 0.002},
               {"name": "Sprint back", "km": 10.0, "net_gradient": -0.002}],
              "typical_road", 15.0, 40,
              [{"name": "Sprint run out", "km": 2.5, "net_gradient": 0.0},
               {"name": "Sprint run back", "km": 2.5, "net_gradient": 0.0}],
              15.0, 0,
              [
                  {"name": "swim_exit", "leg": "SWIM", "limit_minutes_from_start": 30.0, "km": 0.75},
                  {"name": "bike_cutoff", "leg": "BIKE", "limit_minutes_from_start": 95.0, "km": 20.0},
                  {"name": "finish", "leg": "RUN", "limit_minutes_from_start": 130.0, "km": 5.0},
              ],
              [10], 2.5),
    ]

    for course in courses:
        path = OUT / f"{course['golden_course_id']}.json"
        path.write_text(
            json.dumps(course, indent=2, sort_keys=True, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        bike = course["legs"]["BIKE"]
        run = course["legs"]["RUN"]
        print(
            f"{course['golden_course_id']:8s} bike {bike['distance_m']/1000:7.2f} km "
            f"gain {bike['elevation_gain_m']:7.1f} m (B.1 declares {bike['declared_elevation_gain_m']}) | "
            f"run {run['distance_m']/1000:6.2f} km gain {run['elevation_gain_m']:6.1f} m "
            f"(B.1 declares {run['declared_elevation_gain_m']}) -> {path.name}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
